import {  Timezone  } from '../models/models' 

export const timezones: Timezone[] = [
    // { display: "GMT -12:00 IDLW (Baker Island)", value: "IDLW" },
    // { display: "GMT -11:00 NT (Pago Pago)", value: "NT" },
    // { display: "GMT -10:00 AHST (Honolulu)", value: "AHST" },
    // { display: "GMT -09:00 YST (Anchorage)", value: "YST" },
    { display: "GMT -08:00 PST (Los Angeles)", value: "PST" },
    { display: "GMT -07:00 MST (Phoenix)", value: "MST" },
    { display: "GMT -06:00 CST (Chicago)", value: "CST" },
    { display: "GMT -05:00 EST (New York)", value: "EST" },
    // { display: "GMT -04:00 AST (Halifax)", value: "AST" },
    // { display: "GMT -03:30 NST (St. John's)", value: "NST" },
    { display: "GMT -03:00 BRT (São Paulo)", value: "BRT" },
    // { display: "GMT -02:00 AT (South Georgia)", value: "AT" },
    // { display: "GMT -01:00 WAT (Azores)", value: "WAT" },
    { display: "GMT +00:00 GMT (London)", value: "GMT" },
    { display: "GMT +01:00 CET (Paris)", value: "CET" },
    { display: "GMT +02:00 EET (Athens)", value: "EET" },
    { display: "GMT +03:00 BT (Moscow)", value: "BT" },
    { display: "GMT +03:30 IT (Tehran)", value: "IT" },
    { display: "GMT +04:00 ZP4 (Dubai)", value: "ZP4" },
    { display: "GMT +05:00 ZP5 (Tashkent)", value: "ZP5" },
    { display: "GMT +05:30 IST (Mumbai)", value: "IST" },
    { display: "GMT +06:00 ZP6 (Almaty)", value: "ZP6" },
    { display: "GMT +07:00 WAST (Bangkok)", value: "WAST" },
    { display: "GMT +08:00 CHST (Beijing)", value: "CHST" },
    { display: "GMT +09:00 JST (Tokyo)", value: "JST" },
    { display: "GMT +10:00 EAST (Sydney)", value: "EAST" },
    // { display: "GMT +11:00 MET (Solomon Islands)", value: "MET" },
    // { display: "GMT +12:00 NZST (Wellington)", value: "NZST" }
];